### ISSUE TITLE
Issue With MonoLisa Font Displaying Only in Italic on macOS

### ISSUE THREAD

**Issue by diantongren** [d8-bbc11/monolisa#12]
I've encountered an issue on macOS where after installing the MonoLisa font, only the Italic version appears to work properly. All other styles, such as bold or regular, do not display as expected.
This seems to be happening because there are two fonts available on the system that both use the 'MonoLisa' style. Therefore the system defaults to the Italic version.(I am not good at English, translated by gpt)

<img width="152" alt="image" src="https://github.com/d8-bbc11/monolisa/assets/77529255/5dda5d42-1dcb-48db-a4ae-29d5b1054ca0">
<img width="158" alt="image" src="https://github.com/d8-bbc11/monolisa/assets/77529255/dd8a7111-2020-4b8b-81d6-fde8500d7da6">
<img width="911" alt="image" src="https://github.com/d8-bbc11/monolisa/assets/77529255/c869e9bf-75e5-41a6-9edb-af6e75e6c5d9">

**Comment by d8-bbc11** [comment]
try with latest commit, it should work
![image](https://github.com/d8-bbc11/monolisa/assets/159638529/56d275e4-592e-460b-ad37-55c0801b4a17)

**Comment by diantongren** [comment]
It works, than you very much!
