### ISSUE TITLE
Incase this GitHub gets taken down.

### ISSUE THREAD

**Issue by tajoumaru** [d8-bbc11/monolisa#4]
Considering that the creators seem to really love money they probably will try to take this down at one point. Do you have another place to find your medicine? Thanks ДiSC-8 for the effort.

**Comment by d8-bbc11** [comment]
>Do you have another place to find your medicine?

you can expect a `d8-bbc12` account popping up here if this gets taken down 😄

sooner or later i'll open up a tor hidden service specifically for this though

**Comment by d8-bbc11** [comment]
i've noticed other repos with the same premise(font crack) have issues about takedowns open for years, i don't think they'll actually do anything other than be angry at me lol

**Comment by d8-bbc11** [comment]
yeah looks like this the ENDTIMES for this repo, but i got something prepared

http://l7f5lryowxwan5mdq4dys2wy5yaunko2sfogetoei7euejck2ya4mhqd.onion/
