### ISSUE TITLE
Font is missing in JetBrains IDEs

### ISSUE THREAD

**Issue by Verrok** [d8-bbc11/monolisa#5]
Hello, I have installed -normal version of this font, but it didn't appear in Golang, but in works in VS Code
![image](https://github.com/d8-bbc11/monolisa/assets/26070304/7a152554-4706-4f6a-b8f0-d10d77536b28)

I guess it happened because the "Regular" weight is undefined in predefined instances 
https://fontdrop.info/#/?darkmode=true

![image](https://github.com/d8-bbc11/monolisa/assets/26070304/c64f8270-c6b7-40ba-9d6b-4cdac0b6ff31)

**Comment by d8-bbc11** [comment]
try opening the ttf in [fontforge](https://fontforge.org/) and exporting it, afaik it has no support for variable fonts or i'm just doing something wrong, but it should fix the issue if you're only gonna be using the regular variant

tell if it works
