### ISSUE TITLE
Nerd Font version

### ISSUE THREAD

**Issue by mesidex** [d8-bbc11/monolisa#9]
Hi,

Would it be possible to include a variant that has been patched using [Nerd Fonts](https://www.nerdfonts.com/)?

**Comment by d8-bbc11** [comment]
kinda out of scope for this project
[this repo](https://github.com/daylinmorgan/monolisa-nerdfont-patch) works fine for patching monolisa
![image](https://github.com/d8-bbc11/monolisa/assets/159638529/e9787fec-72bf-46a3-8706-b4005e4e26b7)
